base_url = "https://pdhall99.github.io/pen-and-ink"
title = "Pen and ink resources 🖋️"
description = "Resources for pen and ink drawing."
default_language = "en"
theme = "zola-bearblog"
generate_feeds = true
feed_filenames = ["atom.xml"]
generate_sitemap = true
generate_robots_txt = true
compile_sass = false
taxonomies = [
  { name = "tagged", feed = false },
]

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
