base_url = "https://pdhall99.github.io/pen-and-ink"
title = "Pen and ink resources 🖋️"
description = "Resources for pen and ink drawing."
default_language = "en"
generate_feeds = true
feed_filenames = ["atom.xml"]
generate_sitemap = true
generate_robots_txt = true
compile_sass = false
build_search_index = false
taxonomies = [
  { name = "tagged", feed = false },
]

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[extra]
date_format = "%d %b %Y"
webserver_sends_csp_headers = false
language_switcher = false
hide_made_with_line = false

[extra.table_of_contents]
show = false
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
